### PR TITLE
Fixed houdini tab bug

### PR DESCRIPTION
**Pull request by Danielaca18**

### CODE REVIEW

**Comment by Danielaca18** [comment]
I called it houdini cause it dissapears

**Review by zihan001 — COMMENTED** [review]
Seems good to me but idk :)

**Review by Oriyans-sunset — CHANGES_REQUESTED** [review]
the tabs seems to be fixed but there is a weird white bar on the top for me, otherwise seems good :)
Screen Shot 2023-03-09 at 23 29 50

**Review by Sam-Sandhu — CHANGES_REQUESTED** [review]
The bug is fixed and the tabs look good. I'm also getting the same white bar on top of the fragments. Otherwise good to go!

**Review by Isaac-Stamatelakis — APPROVED** [review]
**Seems good to me**

**Pull request closed without merging**
